import { createSupabaseServerClient } from "@/lib/supabase/server";
import { getOpenAlerts } from "@/lib/queries";
import { StatusPill } from "@/components/StatusPill";
import { resolveAlert } from "./actions";

export const dynamic = "force-dynamic";

export default async function AlertsPage() {
  const supabase = createSupabaseServerClient();
  const alerts = await getOpenAlerts(supabase);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold text-white">Alerts</h1>
        <p className="text-sm text-slate-400">Generated by scanning real data (supabase/migrations/0005_alerts_function.sql) — nothing here is hand-typed.</p>
      </div>

      <div className="space-y-2">
        {alerts.map((a) => (
          <div key={a.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-charcoal-700 bg-charcoal-900 p-4">
            <div>
              <div className="mb-1 flex items-center gap-2">
                <StatusPill value={a.severity} />
                <span className="text-xs text-slate-500">{new Date(a.created_at).toLocaleString()}</span>
              </div>
              <p className="text-sm text-white">{a.message}</p>
              {a.recommended_action && <p className="text-xs text-slate-400">Suggested: {a.recommended_action}</p>}
            </div>
            <form action={resolveAlert.bind(null, a.id)}>
              <button className="rounded-md border border-charcoal-600 px-3 py-1.5 text-xs text-slate-200 hover:border-charcoal-500">Mark resolved</button>
            </form>
          </div>
        ))}
        {alerts.length === 0 && (
          <div className="rounded-xl border border-charcoal-700 bg-charcoal-900 p-6 text-center text-sm text-slate-500">No open alerts.</div>
        )}
      </div>
    </div>
  );
}
