#!/usr/bin/env python3
"""
Generates supabase/seed.sql — realistic DEVELOPMENT/STAGING demo data sized
for a solo owner-operator detailing business (not the enterprise volume of
the larger competitor this spec was adapted from).

Run: python3 scripts/generate_seed.py > supabase/seed.sql

This script is deterministic (fixed random seed) so re-running it produces
the same demo data. It is NOT part of the production data path — production
data comes only from the real GoHighLevel / Stripe / Urable / Meta
integrations once connected.
"""
import random
from datetime import datetime, timedelta, date

random.seed(42)

TODAY = date(2026, 8, 26)  # anchor date matches the environment's "today"
START = TODAY - timedelta(days=34)

OWNER_ID = "a0000000-0000-0000-0000-000000000001"

def esc(s):
    if s is None:
        return "null"
    return "'" + str(s).replace("'", "''") + "'"

def uid(prefix, n):
    return f"{prefix}0000000-0000-0000-0000-{n:012d}"

def skip_sunday(d: date) -> date:
    # Business is always closed Sundays -> push to Monday
    if d.weekday() == 6:  # Monday=0 ... Sunday=6
        return d + timedelta(days=1)
    return d

def ts(d: date, hour, minute=0):
    return f"{d.isoformat()} {hour:02d}:{minute:02d}:00-04"

lines = []
def emit(sql):
    lines.append(sql)

emit("-- =============================================================================")
emit("-- DEMO / DEVELOPMENT seed data for Lehrman Mobile Detail LLC.")
emit("-- Generated by scripts/generate_seed.py — DO NOT run against production.")
emit("-- Volumes are sized for a solo owner-operator, not an enterprise team.")
emit("-- =============================================================================")
emit("")
emit(f"insert into auth.users (id, email) values ('{OWNER_ID}', 'nathaniel@lehrmanmobiledetail.com') on conflict do nothing;")
emit(f"insert into profiles (id, full_name, role, phone) values ('{OWNER_ID}', 'Nathaniel', 'owner', '+16165550100') on conflict (id) do nothing;")
emit("")

# lead sources
sources = [
    ("Facebook & Instagram Ads", "facebook_instagram_ads"),
    ("Google Business Profile", "google_business_profile"),
    ("Referral", "referral"),
    ("Existing Customer", "existing_customer"),
    ("Website", "website"),
    ("Unknown", "unknown"),
]
for name, cat in sources:
    emit(f"insert into lead_sources (name, category) values ({esc(name)}, '{cat}') on conflict (name) do nothing;")
emit("")

# services
services = [
    ("Ceramic Coating Package", "ceramic_coating", 120000),
    ("Paint Correction", "paint_correction", 65000),
    ("Full Interior & Exterior Detail", "interior_detail", 27500),
    ("Mobile Detail Express", "exterior_detail", 15000),
]
for name, cat, price in services:
    emit(f"insert into services (name, category, base_price_cents) values ({esc(name)}, '{cat}', {price}) on conflict do nothing;")
emit("")

# goals (owner-editable targets)
goal_rows = [
    ("revenue_sold", "company", 2500000, "monthly"),
    ("cash_collected", "company", 2000000, "monthly"),
    ("cash_collected", "company", 500000, "weekly"),
    ("dials", "company", 15, "daily"),
    ("conversations", "company", 5, "daily"),
    ("appointments_booked", "company", 20, "monthly"),
    ("show_rate_pct", "company", 80, "monthly"),
    ("close_rate_pct", "company", 45, "monthly"),
    ("average_ticket_cents", "company", 45000, "monthly"),
    ("speed_to_lead_minutes", "company", 5, "monthly"),
]
for metric, scope, target, period in goal_rows:
    emit(f"insert into goals (metric_key, scope, period, target_value, effective_date, created_by) "
         f"values ('{metric}', '{scope}', '{period}', {target}, '{START.isoformat()}', '{OWNER_ID}');")
emit("")

# ad spend - meta only, modest small-business budget
for i in range(18):
    d = START + timedelta(days=i * 2)
    spend = random.randint(2000, 5500)  # $20-$55/day-ish, spaced every 2 days
    leads_attr = random.randint(0, 2)
    emit(f"insert into ad_spend (external_id, platform, campaign_name, spend_date, spend_cents, leads_attributed) "
         f"values ('meta-{i+1}', 'meta', 'GR Detailing - Leads', '{d.isoformat()}', {spend}, {leads_attr}) on conflict do nothing;")
emit("")

source_names = [s[0] for s in sources]
source_weights = [0.40, 0.20, 0.15, 0.10, 0.10, 0.05]

service_names = [s[0] for s in services]
service_prices = {s[0]: s[2] for s in services}
service_weights = [0.30, 0.20, 0.35, 0.15]

# Distribution of current stage across the 34 leads generated, oldest first.
# Reflects real funnel drop-off (see docs/kpi-dictionary.md example).
stage_plan = (
    ["new_lead"] * 2 +
    ["attempting_contact"] * 4 +
    ["contacted"] * 4 +
    ["qualified"] * 3 +
    ["appointment_booked"] * 3 +
    ["appointment_confirmed"] * 2 +
    ["showed"] * 2 +
    ["sold"] * 3 +
    ["deposit_collected"] * 2 +
    ["paid_in_full"] * 2 +
    ["job_completed"] * 4 +
    ["review_requested"] * 1 +
    ["lost"] * 3
)
random.shuffle(stage_plan)

HAS_OPP_STAGES = {
    "qualified", "appointment_booked", "appointment_confirmed", "showed", "sold",
    "deposit_collected", "paid_in_full", "job_completed", "review_requested", "lost",
}
STAGE_ORDER = [
    "new_lead", "attempting_contact", "contacted", "qualified", "appointment_booked",
    "appointment_confirmed", "showed", "sold", "deposit_collected", "paid_in_full",
    "job_completed", "review_requested",
]

lead_counter = 0
opp_counter = 0
appt_counter = 0
payment_counter = 0
job_counter = 0
activity_counter = 0
followup_counter = 0

for idx, stage in enumerate(stage_plan):
    lead_counter += 1
    lead_id = uid("b", lead_counter)
    # spread creation across the last 34 days, most-progressed leads oldest
    created_day = START + timedelta(days=idx)
    created_ts = ts(created_day, random.choice([9, 10, 11, 13, 14, 15, 16]), random.choice([0, 15, 30, 45]))

    src = random.choices(source_names, weights=source_weights, k=1)[0]
    attribution_missing = "false"
    src_sql = f"(select id from lead_sources where name = {esc(src)})"
    if src == "Unknown" and random.random() < 0.6:
        attribution_missing = "true"

    first_names = ["Alex", "Jordan", "Taylor", "Sam", "Morgan", "Casey", "Riley", "Drew",
                   "Cameron", "Jamie", "Avery", "Peyton", "Reese", "Quinn", "Sydney", "Rowan"]
    last_names = ["Bennett", "Hayes", "Foster", "Sutton", "Reyes", "Coleman", "Vance", "Marsh",
                  "Blake", "Doyle", "Nash", "Pratt", "Chase", "Dunn", "Kerr", "Lowry"]
    fname = random.choice(first_names)
    lname = random.choice(last_names)
    phone = f"+1616555{1000 + lead_counter:04d}"

    temperature = "unset"
    first_contacted_at = "null"
    last_contacted_at = "null"
    if stage != "new_lead":
        temperature = random.choices(["hot", "warm", "cold"], weights=[0.5, 0.35, 0.15], k=1)[0]
        contact_delay_min = random.choice([2, 4, 8, 15, 40, 90])
        fc_dt = datetime.combine(created_day, datetime.min.time()) + timedelta(hours=random.choice([9,10,11,13,14,15]), minutes=contact_delay_min)
        first_contacted_at = f"'{fc_dt.isoformat()}-04'"
        last_contacted_at = first_contacted_at

    lost_reason = "null"
    if stage == "lost":
        lost_reason = esc(random.choice(["Went with a competitor", "Price too high", "No longer needs service", "Unresponsive after quote"]))

    assigned = f"'{OWNER_ID}'"
    emit(
        f"insert into leads (id, external_id, source_platform, first_name, last_name, phone, email, "
        f"lead_source_id, attribution_missing, assigned_to, stage, temperature, created_at, first_contacted_at, "
        f"last_contacted_at, lost_reason) values ("
        f"'{lead_id}', 'ghl-demo-{lead_counter}', 'gohighlevel', {esc(fname)}, {esc(lname)}, {esc(phone)}, "
        f"{esc(fname.lower()+'.'+lname.lower()+'@example.com')}, {src_sql}, {attribution_missing}, {assigned}, "
        f"'{stage}', '{temperature}', '{created_ts}', {first_contacted_at}, {last_contacted_at}, {lost_reason});"
    )

    # activities: a couple of dials/calls/texts around first contact for any lead beyond new_lead
    if stage != "new_lead":
        for k in range(random.randint(1, 3)):
            activity_counter += 1
            a_type = random.choices(["dial", "connected_call", "text"], weights=[0.4, 0.35, 0.25], k=1)[0]
            occurred = f"'{created_ts}'::timestamptz + interval '{k*35} minutes'"
            duration = "null" if a_type != "connected_call" else str(random.randint(60, 480))
            outcome = esc({"dial": "no_answer", "connected_call": "answered", "text": "sent"}[a_type])
            emit(
                f"insert into activities (lead_id, performed_by, type, direction, outcome, duration_seconds, occurred_at) "
                f"values ('{lead_id}', '{OWNER_ID}', '{a_type}', 'outbound', {outcome}, {duration}, {occurred});"
            )

    opp_id = None
    if stage in HAS_OPP_STAGES:
        opp_counter += 1
        opp_id = uid("c", opp_counter)
        svc = random.choices(service_names, weights=service_weights, k=1)[0]
        price = service_prices[svc]
        opp_created = created_ts
        probability = {
            "qualified": 40, "appointment_booked": 55, "appointment_confirmed": 65,
            "showed": 70, "sold": 100, "deposit_collected": 100, "paid_in_full": 100,
            "job_completed": 100, "review_requested": 100, "lost": 0,
        }[stage]
        opp_lost_reason = lost_reason
        emit(
            f"insert into opportunities (id, external_id, source_platform, lead_id, service_id, vehicle_description, "
            f"estimated_value_cents, stage, probability, location, salesperson_id, lost_reason, created_at) values ("
            f"'{opp_id}', 'ghl-opp-{opp_counter}', 'gohighlevel', '{lead_id}', "
            f"(select id from services where name = {esc(svc)}), 'Customer vehicle', {price}, '{stage}', {probability}, "
            f"'Grand Rapids', '{OWNER_ID}', {opp_lost_reason}, '{opp_created}');"
        )

        # The opportunity is inserted directly at its terminal demo stage, so
        # the INSERT trigger only logs ONE stage_history row (that terminal
        # stage). Anything that progressed past 'sold' would otherwise never
        # show up in "revenue sold" reporting (which keys off to_stage =
        # 'sold'). Backfill a synthetic 'sold' transition for those so the
        # demo's revenue-sold view reflects reality: once a deal is sold it
        # stays counted as sold even after it's paid/completed.
        if stage in ("deposit_collected", "paid_in_full", "job_completed", "review_requested"):
            emit(
                f"insert into stage_history (entity_type, entity_id, from_stage, to_stage, changed_at) "
                f"values ('opportunity', '{opp_id}', 'qualified', 'sold', '{opp_created}');"
            )

        # appointment for anything at appointment_booked or beyond (except lost with no appt)
        if stage != "lost" or random.random() < 0.3:
            appt_counter += 1
            appt_day = skip_sunday(created_day + timedelta(days=random.randint(1, 4)))
            appt_ts = ts(appt_day, random.choice([9, 11, 13, 15]))
            if stage in STAGE_ORDER and STAGE_ORDER.index(stage) >= STAGE_ORDER.index("appointment_confirmed"):
                confirmed = "true"
            else:
                confirmed = "false"
            showed_val = "null"
            if stage in STAGE_ORDER and STAGE_ORDER.index(stage) >= STAGE_ORDER.index("showed"):
                showed_val = "true"
            elif stage == "lost":
                showed_val = random.choice(["true", "false"])
            emit(
                f"insert into appointments (opportunity_id, external_id, source_platform, scheduled_at, confirmed, showed, location) "
                f"values ('{opp_id}', 'urable-appt-{appt_counter}', 'urable', '{appt_ts}', {confirmed}, {showed_val}, 'Grand Rapids');"
            )

        # payments for sold and beyond
        if stage in ("sold", "deposit_collected", "paid_in_full", "job_completed", "review_requested"):
            payment_counter += 1
            deposit_amt = int(price * 0.3)
            dep_day = created_day + timedelta(days=random.randint(0, 2))
            emit(
                f"insert into payments (external_id, source_platform, opportunity_id, amount_cents, type, status, processed_at) "
                f"values ('pi_demo_{payment_counter}', 'stripe', '{opp_id}', {deposit_amt}, 'deposit', 'succeeded', '{ts(dep_day, 10)}');"
            )
            if stage in ("paid_in_full", "job_completed", "review_requested"):
                payment_counter += 1
                bal_amt = price - deposit_amt
                bal_day = min(dep_day + timedelta(days=random.randint(1, 5)), TODAY)
                emit(
                    f"insert into payments (external_id, source_platform, opportunity_id, amount_cents, type, status, processed_at) "
                    f"values ('pi_demo_{payment_counter}', 'stripe', '{opp_id}', {bal_amt}, 'balance', 'succeeded', '{ts(bal_day, 15)}');"
                )

        # jobs for job_completed / review_requested
        if stage in ("job_completed", "review_requested"):
            job_counter += 1
            job_day = skip_sunday(created_day + timedelta(days=random.randint(3, 7)))
            emit(
                f"insert into jobs (external_id, source_platform, opportunity_id, scheduled_at, completed_at, status) "
                f"values ('urable-job-{job_counter}', 'urable', '{opp_id}', '{ts(job_day, 10)}', '{ts(job_day, 14)}', 'completed');"
            )

# One deliberately-broken payment to exercise the failed-payment alert
payment_counter += 1
emit(
    f"insert into payments (external_id, source_platform, opportunity_id, amount_cents, type, status, processed_at) "
    f"select 'pi_demo_fail_{payment_counter}', 'stripe', id, estimated_value_cents / 3, 'deposit', 'failed', now() - interval '2 days' "
    f"from opportunities where stage = 'sold' limit 1;"
)

# Two very recent, uncontacted leads (created today / yesterday) so the
# Daily Command Center's "not contacted within 5 minutes" alert has
# something real to show.
for i in range(2):
    lead_counter += 1
    lead_id = uid("b", lead_counter)
    d = TODAY - timedelta(days=i)
    created_ts_recent = ts(d, 8 + i, 10)
    src_sql = "(select id from lead_sources where name = 'Facebook & Instagram Ads')"
    emit(
        f"insert into leads (id, external_id, source_platform, first_name, last_name, phone, email, "
        f"lead_source_id, assigned_to, stage, temperature, created_at) values ("
        f"'{lead_id}', 'ghl-demo-{lead_counter}', 'gohighlevel', 'New', 'Inquiry{i+1}', '+16165559{900+i}', "
        f"'new.inquiry{i+1}@example.com', {src_sql}, '{OWNER_ID}', 'new_lead', 'unset', '{created_ts_recent}');"
    )

emit("")
emit("-- The stage_history trigger stamps changed_at = insert time (now()), which")
emit("-- would collapse every seeded deal onto the day this script was run. Backdate")
emit("-- each entity's single history row to the fabricated created_at so daily/")
emit("-- weekly trend views show a realistic spread. NOTE: because seed opportunities")
emit("-- are inserted directly at their terminal demo stage (not simulated through")
emit("-- every intermediate transition), this backdating is a simplification for")
emit("-- demo purposes only — see docs/known-limitations.md.")
emit("update stage_history sh set changed_at = o.created_at "
     "from opportunities o where sh.entity_type = 'opportunity' and sh.entity_id = o.id;")
emit("update stage_history sh set changed_at = l.created_at "
     "from leads l where sh.entity_type = 'lead' and sh.entity_id = l.id;")
emit("")
emit("-- Refresh alerts based on the seeded data above.")
emit("select generate_alerts();")

print("\n".join(lines))
